models/TrainForm.php
<?php

namespace app\models;

use yii\base\Model;

class TrainForm extends Model
{
  public $date;
  public $train_num;
  public $from;
  public $where;

  public function rules()
  {
      return [
          [['date', 'train_num', 'from', 'where'], 'required'],
      ];
  }

  public function attributeLabels() {
    return [
      'train_num' => 'Номер поезда',
      'date'      => 'Дата отправления',
      'from'      => 'Код станции отправления',
      'where'     => 'Код станции прибытия',
    ];
  }

}

controllers/TrainController.php
<?php

namespace app\controllers;


use Yii;
use yii\filters\AccessControl;
use yii\web\Response;

use yii\filters\VerbFilter;

use app\models\User;
use app\models\Api;
use app\models\ExpressApi;
use app\models\TrainForm;
use app\models\StationForm;

use yii\helpers\ArrayHelper;
use yii\helpers\Url;


class TrainController extends BaseController
{

    // public function behaviors()
    // {
    //     return [
    //         'access' => [
    //             'class' => AccessControl::className(),
    //             'rules' => [
    //                 [
    //                     'actions' => ['index', 'suggest', 'form', 'info'],
    //                     'allow' => true,
    //                     'roles' => ['@'],
    //                 ],
    //             ],
    //         ],
    //     ];
    // }


    /**
    * Displays to home page.
    *
    * @return string
    */
    public function actionIndex()
    {
        $train_num = Yii::$app->request->get('train_num');
        $date = Yii::$app->request->get('date');
        $from = Yii::$app->request->get('from');
        $where = Yii::$app->request->get('where');
        $session = Yii::$app->session;
        $session->open();

        $stationform = new StationForm;

        if (isset($_SESSION['wherefrom']) && isset($_SESSION['wherein']) && isset($_SESSION['datetrain'])) {
            $stationform->wherefrom = $_SESSION['wherefrom'];
            $stationform->wherein = $_SESSION['wherein'];
            $stationform->date = $_SESSION['datetrain'];
        }

        if(isset($train_num) && isset($date) && isset($from) && isset($where)) {
            $trainform = new TrainForm;
            $trainform->from = $from;
            $trainform->where = $where;
            $trainform->train_num = $train_num;
            $trainform->date = $date;

            return $this->render('index', compact('trainform'));
        }

        return $this->render('index', compact('stationform'));
    }

    /**
    * Display list stations
    *
    * @return JSON array
    */
    public function actionSuggest($name=null)
    {
        if (!Yii::$app->request->isAjax || !isset($name)) {
            return $this->goHome();
        }

        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = ExpressApi::Suggest($name);

        $items = [];

        foreach ($response->Station as $item) {
            $items['items'][] = ['id' => $item->attributes()->Code, 'text' => $item->NameFull];
        }

        return $items;
    }

    /**
    * Makes form info about train, stations
    *
    * @return redirect
    */
    public function actionForm()
    {
        if(!Yii::$app->request->post()) {
            return $this->goBack();
        }

        $post = Yii::$app->request->post();
        $session = Yii::$app->session;
        $session->open();
        $_SESSION['station'] = $post['station'];
        $_SESSION['train_num'] = $post['train_num'];
        $_SESSION['wagon_num'] = $post['wagon_num'];
        $_SESSION['stop'] = $post['waiting_time'];
        $_SESSION['data_train']  = Yii::$app->formatter->format($post['date'], 'timestamp') - 3 * 3600;
        $_SESSION['time'] = Yii::$app->formatter->asDate($_SESSION['data_train'], 'HH:mm');
        $_SESSION['order_city'] = $post['city'];
        $_SESSION['order_city_id'] = $post['city_id'];

        return $this->redirect(Url::toRoute(['/go-by-train'], 'https'));
    }

    /**
    * Info about stations
    *
    * @return array
    */
    public function actionInfo($code=null)
    {
        if (Yii::$app->request->isAjax) {
            if(isset($code)) {
                $token = Yii::$app->user->isGuest ? $_SESSION['token'] : Yii::$app->user->identity->accessToken;
                $items = Api::stations_list($token, $code , true, null, 1)->items;
                if (!empty($items[0]->city->available)) {
                    return json_encode($items[0]->city);
                } else {
                    return 0;
                }
            } else {
                return 0;
            }
        }
        return $this->goHome();
    }

    /**
     *
     */
    public function actionList()
    {
        $wherefrom = Yii::$app->request->get('wherefrom');
        $wherein = Yii::$app->request->get('wherein');
        $date = Yii::$app->request->get('date');

        if(isset($wherefrom) && isset($wherein) && isset($date)) {
            $_SESSION['wherefrom'] = $wherefrom;
            $_SESSION['wherein'] = $wherein;
            $_SESSION['datetrain'] = $date;
            return $this->redirect(Url::to(['/train'], 'https'));
        }
    }

}

views/train/index.php
<?php
use app\components\widgets\TrainsWidget;
use yii\jui\DatePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

use kartik\select2\Select2;
use yii\web\JsExpression;

$this->title = 'Заказ готовой еды прямо к вагону поезда |FOOD BALL';
$this->registerMetaTag(['name' => 'description', 'content' => 'С помощью сервиса FOOD BALL у тебя есть возможность заказать доставку суши, бургеров, пиццы, шашлыков к вагону поезда, в котором ты едешь.']);

$route = Url::to(['/train/suggest'], 'https');
$formatJs = <<< 'JS'
var formatRepoSelection = function (repo) {
    return repo.text;
}
JS;

$this->registerJs($formatJs, yii\web\View::POS_HEAD);

$resultsJs = <<< 'JS'
function (data) {
    return {
        results: data.items,
    };
}
JS;

if(isset($stationform->date)) {
  $this->registerJs("
    $('tbody td').on('click', function (e) {
        var code = $(this).closest('tr').data('key');
        var from = $(this).closest('tr').data('from');
        var where = $(this).closest('tr').data('where');
        if(e.target == this)
location.href = '" . Url::to(['/train'], 'https') . "?train_num=' + code +
'&date=' + '$stationform->date' + '&from=' + from + '&where=' + where;
    });
", yii\web\View::POS_END);
}

?>

<section class="stations_search">
      <div class="container">
        <div class="row">
          <article class="col-lg-12">
            <div class="order-train_way active">
              <h3 class="order-train-way_title order-train-way_title__top">Доставка к поезду</h3>
              <h3 class="order-train-way_title order-train-way_title__changed-text"></h3>
              <?php if(isset($stationform) && !isset($stationform->date)) { ?>
                <?php $this->registerJsFile('/js/totrainlist.js', ['depends' => 'app\assets\IndexAsset']); ?>
                <?php $form = ActiveForm::begin([
                    'options' => ['class' => 'form-inline'],
                ])
                ?>

                <?= $form->field($stationform, 'wherefrom')->widget(Select2::classname(), [
					'language' => 'ru',
                    'value' => '1',
                    'initValueText' => 'Станция отправления', // set the initial display text
                    'options' => ['class' => 'order-train-way_input', 'id' => 'selecttt',
                      'onclick' => 'yaCounter44742985.reachGoal(\'otpravlenie\'); return true;'],
                    'pluginOptions' => [
                        'minimumInputLength' => 3,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return 'Ожидайте результат...'; }"),
                        ],
                        'ajax' => [
                            'url' => $route,
                            'dataType' => 'json',
                            'delay' => 2000,
                            'data' => new JsExpression('function(params) { return {name:params.term}; }'),
                            'processResults' => new JsExpression($resultsJs),
                            'cache' => true
                          ],
                     ],
                ]);?>

                <div class="form-group">
                    <img src="/image/arrows.png" alt="" class="order-train-way_arrows">
                </div>

                <?= $form->field($stationform, 'wherein')->widget(Select2::classname(), [
					'language' => 'ru',
                    'value' => '1',
                    'initValueText' => 'Станция прибытиия', // set the initial display text
                    'options' => ['class' => 'order-train-way_input'],
                    'pluginOptions' => [
                        'minimumInputLength' => 3,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return 'Ожидайте результат...'; }"),
                        ],
                        'ajax' => [
                            'url' => $route,
                            'dataType' => 'json',
                            'delay' => 2000,
                            'data' => new JsExpression('function(params) { return {name:params.term}; }'),
                            'processResults' => new JsExpression($resultsJs),
                            'cache' => true
                          ],
                     ],
                ]);?>

                <?= $form->field($stationform,'date')->widget(DatePicker::className(),['options' => ['class' => 'order-train-way_input', 'placeholder' => 'Дата отправления', 'type' => 'text'], 'dateFormat' => 'dd.MM.yyyy'])->label(false) ?>

                <?= Html::submitButton('<i class="fa fa-search" aria-hidden="true"></i>Найти', ['class' => 'order-content_btn click', 'onclick' => 'yaCounter44742985.reachGoal(\'serchtrain\'); return getTrainList();']) ?>

                <?php ActiveForm::end() ?>
              <? } ?>
            </div>
          </article>
        </div>
      </div>
    </section>

    <main class="stations_train">
      <section class="container">
        <article class="row">
          <div class="col-lg-12">
            <?php if(isset($trainform->train_num)) { ?>
              <?php $this->title = 'Список станций'; ?>
              <?php $this->registerJsFile('/js/tostations.js', ['depends' => 'app\assets\IndexAsset']); ?>
            <div class="stations-train_info" data-local=<?= $_SESSION['trtime']; ?>>
              <div class="stations-train_borders">
                <table class="stations-train_table" data-id="list_of_stations">
                  <thead class="stations-train-table_header">
                    <tr class="stations-train-table-header_row">
                      <th class="stations-train-table-header_cell"></th>
                      <th class="stations-train-table-header_cell">Станция</th>
                      <th class="stations-train-table-header_cell">Прибытие</th>
                      <th class="stations-train-table-header_cell">Стоянка</th>
                      <th class="stations-train-table-header_cell">Отправление</th>
                    </tr>
                  </thead>
                  <tbody class="stations-train-table_body">
                   <?= TrainsWidget::widget(['tpl' => 'stations', 'trainform' => $trainform]); ?>
                  </tbody>
                </table>
              </div>
            </div>
            <?php } elseif (isset($stationform->wherefrom)) { ?>
              <?php $this->title = 'Список поездов'; ?>
              <div class="stations-train_info">
                <div class="stations-train_borders">
                  <table class="stations-train_table" data-id="list_of_trains">
                    <thead class="stations-train-table_header">
                      <tr class="stations-train-table-header_row">
                        <th class="stations-train-table-header_cell">Номер поезда</th>
                        <th class="stations-train-table-header_cell">Станция отправления</th>
                        <th class="stations-train-table-header_cell">Станция прибытия</th>
                      </tr>
                    </thead>
                    <tbody class="stations-train-table_body">
                     <?= TrainsWidget::widget(['tpl' => 'trains_list', 'stationform' => $stationform]); ?>
                    </tbody>
                  </table>
                </div>
              </div>
            <?php  } ?>
          </div>
        </article>
      </section>
    </main>